name: test workflow for diff

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  echo_changed_files:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_DEV }}
      SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
    permissions:
      contents: read
      id-token: write
    steps:
    - name: Check out the repo
      uses: actions/checkout@v3
    - name: Get changed files
      id: changed-files
      uses: tj-actions/changed-files@v45
    - name: Echo changed files
      run: echo ${{ steps.changed-files.outputs.all_modified_files }}
